// Lazy-loaded PDF renderers for quotes + invoices.
//
// Returns a Blob so the caller can decide how to surface it (in-app
// preview modal, new tab, forced download). The actual jsPDF +
// jspdf-autotable imports live behind dynamic `import()` so the
// ~250 KB library only ships on first click.

import type {
  InvoiceDiscount,
  InvoiceDoc,
  LineItem,
  QuoteDoc,
  WithId,
} from "@/firebase/interfaces";
import type { Timestamp } from "firebase/firestore";

export interface PartyInfo {
  tradesperson: {
    name: string;
    companyName: string | null;
    // When set, the PDF header band renders this in place of the Blue Seal
    // wordmark + uses the tradesperson's company name as the headline. The
    // platform stays attributed in the footer ("Generated by Blue Seal").
    companyLogoUrl: string | null;
    address: string | null;
    phone: string | null;
    email: string | null;
    gstNumber: string | null;
  };
  client: {
    name: string;
    email: string | null;
    phone: string | null;
    address: string | null;
  };
}

interface RenderTotals {
  subtotal: number;
  discount: InvoiceDiscount | null;
  discountAmount: number;
  taxTotal: number;
  /**
   * Upfront fee that was already collected and is being credited against this
   * invoice. Optional + zero-tolerant so quote rendering (which never carries
   * a credit) doesn't have to thread an extra value through.
   */
  upfrontFeeCreditAmount?: number;
  total: number;
  currency: string;
}

interface DocSummary {
  kind: "Quote" | "Invoice";
  number: string;
  issuedLabel: string;
  issuedDate: string;
  validUntil?: string | null;
  noteToClient?: string | null;
  paymentInstructions?: string | null;
  terms?: string | null;
}

// Brand palette — pulled into the PDF as RGB tuples so the rendered
// file is self-contained. Mirrors the CSS custom properties in
// src/assets/main.css so on-screen and on-paper Blue Seal feel like
// the same brand.
//   --bs-blue-dark   #1d406a → header band, table head, accents
//   --bs-blue        #49a1d3 → secondary band, links
//   --bs-blue-light  #a0d6f1 → ultra-soft panels
//   --bs-amber       #f59e0b → total highlight
//   --bs-bg          #f5f7fb → paper-alt panels
const BRAND = {
  blueDark: [29, 64, 106] as const, // #1d406a
  blue: [73, 161, 211] as const, // #49a1d3
  blueLight: [160, 214, 241] as const, // #a0d6f1
  bluePanel: [231, 242, 250] as const, // computed ~10% mix of blue on white
  amber: [245, 158, 11] as const, // #f59e0b
  ink: [17, 24, 39] as const, // #111827
  muted: [107, 114, 128] as const, // #6b7280
  border: [229, 231, 235] as const, // #e5e7eb
  paperAlt: [245, 247, 251] as const, // #f5f7fb
};

function fmtMoney(cents: number, currency = "CAD"): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency,
  }).format(cents / 100);
}

function fmtDate(t: Timestamp | null | undefined): string {
  if (!t) return "—";
  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(t.toDate());
}

// Module-level cache so the logo PNG is only fetched + base64-encoded
// once per page session. The data URL stays in memory for the rest of
// the tab's lifetime.
let logoDataUrlCache: string | null = null;
async function loadLogoDataUrl(): Promise<string | null> {
  if (logoDataUrlCache) return logoDataUrlCache;
  try {
    const res = await fetch("/icons/blueseal_logo.png");
    if (!res.ok) return null;
    const blob = await res.blob();
    const reader = new FileReader();
    const dataUrl = await new Promise<string>((resolve, reject) => {
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
    logoDataUrlCache = dataUrl;
    return dataUrl;
  } catch {
    return null;
  }
}

// Fetches a remote image (typically a Firebase Storage download URL) and
// returns a base64 data URL suitable for jsPDF's addImage. No cache — the
// tradesperson logo URL changes when they re-upload, and we want the next
// render to reflect that. Returns null on any failure so the caller can
// fall back to the platform Blue Seal mark.
async function loadRemoteImageAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    const reader = new FileReader();
    return await new Promise<string>((resolve, reject) => {
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// jsPDF addImage takes a format hint; infer it from the data URL prefix so
// callers don't have to worry about WebP-vs-PNG-vs-JPEG. Falls back to
// "PNG" which jsPDF always supports.
function inferImageFormat(dataUrl: string): string {
  const match = /^data:image\/([a-z]+);/i.exec(dataUrl);
  if (!match) return "PNG";
  const fmt = match[1].toUpperCase();
  return fmt === "JPG" ? "JPEG" : fmt;
}

async function renderPdf(
  summary: DocSummary,
  party: PartyInfo,
  lineItems: LineItem[],
  totals: RenderTotals,
): Promise<Blob> {
  // Lazy-imports keep the main bundle slim. jspdf-autotable mutates the
  // jsPDF instance, so it has to be imported after jsPDF. Tradie logo is
  // loaded in parallel; falls back to the platform Blue Seal mark when
  // unset or the fetch fails.
  const tradieLogoUrl = party.tradesperson.companyLogoUrl;
  const [{ jsPDF }, autoTableMod, blueSealLogoDataUrl, tradieLogoDataUrl] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
    loadLogoDataUrl(),
    tradieLogoUrl ? loadRemoteImageAsDataUrl(tradieLogoUrl) : Promise.resolve(null),
  ]);
  const autoTable = autoTableMod.default;

  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;

  // ============== HEADER BAND ==============
  // Brand band uses --bs-blue-dark as the primary surface with a thin
  // --bs-blue accent strip underneath for depth — softer than a pure
  // flat fill. Total band height 88pt so the logo + wordmark have room
  // without crowding the doc-number on the right.
  const bandHeight = 88;
  const accentY = bandHeight - 6;
  doc.setFillColor(...BRAND.blueDark);
  doc.rect(0, 0, pageWidth, bandHeight, "F");
  doc.setFillColor(...BRAND.blue);
  doc.rect(0, accentY, pageWidth, 6, "F");

  // Logo on the left. jsPDF expects width/height in the doc's units
  // (pt). The source asset is square — render at 38pt so the band has
  // breathing room above and below. When the tradesperson has uploaded
  // a company logo, it takes the header slot and their company name
  // (or display name as fallback) becomes the wordmark; platform
  // attribution moves to the footer ("Generated by Blue Seal").
  const logoSize = 38;
  const logoX = margin;
  const logoY = 24;
  let textXAfterLogo = margin;
  const headerLogoDataUrl = tradieLogoDataUrl ?? blueSealLogoDataUrl;
  if (headerLogoDataUrl) {
    try {
      doc.addImage(
        headerLogoDataUrl,
        inferImageFormat(headerLogoDataUrl),
        logoX,
        logoY,
        logoSize,
        logoSize,
      );
      textXAfterLogo = logoX + logoSize + 14;
    } catch {
      /* image add can fail on malformed data URL — fall back to text-only */
    }
  }

  // Wordmark — tradesperson's company name (or display name) when their
  // logo is in use; Blue Seal otherwise. Bold Helvetica stands in for the
  // brand's Concert One until we ship embedded fonts.
  const usingTradieLogo = tradieLogoDataUrl != null;
  const wordmarkTitle = usingTradieLogo
    ? (party.tradesperson.companyName?.trim() || party.tradesperson.name)
    : "Blue Seal";
  const wordmarkSubtitle = usingTradieLogo ? "Verified Tradesperson" : "Verified Trades";
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(wordmarkTitle, textXAfterLogo, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...BRAND.blueLight);
  doc.text(wordmarkSubtitle, textXAfterLogo, 58);

  // Doc kind + number on the right
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(...BRAND.blueLight);
  doc.text(summary.kind.toUpperCase(), pageWidth - margin, 32, {
    align: "right",
  });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text(summary.number, pageWidth - margin, 52, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...BRAND.blueLight);
  doc.text(`${summary.issuedLabel}: ${summary.issuedDate}`, pageWidth - margin, 68, {
    align: "right",
  });

  // ============== FROM / BILL TO PANEL ==============
  // Two columns sitting just below the header band. Soft panels with
  // a subtle border so the contact info reads as its own block without
  // shouting against the brand colour.
  const panelY = bandHeight + 24;
  const panelGap = 16;
  const colWidth = (pageWidth - margin * 2 - panelGap) / 2;
  const leftX = margin;
  const rightX = margin + colWidth + panelGap;
  const panelPadX = 14;
  const panelPadY = 14;
  // Fixed-height panel sized to fit: heading + name + companyName + up to
  // 4 contact lines (address, phone, email, GST/HST) without overflow.
  const panelHeight = 112;

  doc.setDrawColor(...BRAND.border);
  doc.setFillColor(...BRAND.paperAlt);
  doc.roundedRect(leftX, panelY, colWidth, panelHeight, 6, 6, "FD");
  doc.roundedRect(rightX, panelY, colWidth, panelHeight, 6, 6, "FD");

  const writePartyBlock = (
    x: number,
    heading: string,
    name: string,
    companyName: string | null,
    lines: Array<string | null>,
  ) => {
    let y = panelY + panelPadY + 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.blue);
    doc.text(heading, x + panelPadX, y);

    y += 14;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11.5);
    doc.setTextColor(...BRAND.ink);
    doc.text(name, x + panelPadX, y);

    if (companyName) {
      y += 13;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...BRAND.ink);
      doc.text(companyName, x + panelPadX, y);
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.muted);
    for (const line of lines) {
      if (!line) continue;
      y += 12;
      const wrapped = doc.splitTextToSize(line, colWidth - panelPadX * 2);
      doc.text(wrapped, x + panelPadX, y);
      if (Array.isArray(wrapped) && wrapped.length > 1) {
        y += (wrapped.length - 1) * 11;
      }
    }
  };

  writePartyBlock(
    leftX,
    "FROM",
    party.tradesperson.name,
    party.tradesperson.companyName,
    [
      party.tradesperson.address,
      party.tradesperson.phone,
      party.tradesperson.email,
      // CRA documentary requirement — GST/HST registrants must show their
      // number on invoices for clients to claim input tax credits.
      party.tradesperson.gstNumber
        ? `GST/HST: ${party.tradesperson.gstNumber}`
        : null,
    ],
  );
  writePartyBlock(
    rightX,
    summary.kind === "Invoice" ? "BILL TO" : "PREPARED FOR",
    party.client.name,
    null,
    [
      party.client.address,
      party.client.phone,
      party.client.email,
    ],
  );

  let cursorY = panelY + panelHeight + 24;

  // Optional client note — italic pull-quote.
  if (summary.noteToClient) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.ink);
    const noteLines = doc.splitTextToSize(
      `"${summary.noteToClient}"`,
      pageWidth - margin * 2,
    );
    doc.text(noteLines, margin, cursorY);
    cursorY += noteLines.length * 13 + 14;
  }

  // ============== LINE ITEMS TABLE ==============
  // Line total includes tax — `Qty × Unit price × (1 + taxRate)` — so a
  // row with "Tax 13 %" visibly reflects that 13 % in its line total.
  // The pre-tax subtotal + tax breakdown still appears in the totals
  // card so the math stays auditable.
  const tableBody = lineItems.map((li) => {
    const lineSubtotal = li.quantity * li.unitPrice;
    const lineWithTax = Math.round(lineSubtotal * (1 + li.taxRate));
    return [
      li.description,
      li.quantity.toString(),
      fmtMoney(li.unitPrice, totals.currency),
      `${(li.taxRate * 100).toFixed(1)}%`,
      fmtMoney(lineWithTax, totals.currency),
    ];
  });

  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [["Description", "Qty", "Unit price", "Tax %", "Line total"]],
    body: tableBody,
    headStyles: {
      fillColor: [...BRAND.blueDark],
      textColor: 255,
      fontSize: 10,
      fontStyle: "bold",
      cellPadding: 10,
    },
    bodyStyles: {
      fontSize: 10,
      textColor: [...BRAND.ink],
      cellPadding: 10,
    },
    alternateRowStyles: { fillColor: [...BRAND.paperAlt] },
    columnStyles: {
      1: { halign: "right", cellWidth: 50 },
      2: { halign: "right", cellWidth: 90 },
      3: { halign: "right", cellWidth: 60 },
      4: { halign: "right", cellWidth: 90 },
    },
    theme: "plain",
    styles: { lineColor: [...BRAND.border], lineWidth: 0.5 },
  });

  // @ts-expect-error autoTable attaches lastAutoTable to the doc at runtime
  const tableEndY: number = (doc.lastAutoTable?.finalY ?? cursorY) + 18;

  // ============== TOTALS CARD ==============
  const totalsBoxWidth = 230;
  const totalsX = pageWidth - margin - totalsBoxWidth;
  const labelX = totalsX + 16;
  const valueX = totalsX + totalsBoxWidth - 16;
  const rowHeight = 18;
  const hasDiscount = totals.discountAmount > 0;
  const upfrontCreditCents = Math.max(0, totals.upfrontFeeCreditAmount ?? 0);
  const hasUpfrontCredit = upfrontCreditCents > 0;
  // subtotal + tax (+ discount) (+ upfront credit)
  const innerRows = 2 + (hasDiscount ? 1 : 0) + (hasUpfrontCredit ? 1 : 0);
  const totalsBoxHeight = innerRows * rowHeight + 50;

  doc.setDrawColor(...BRAND.border);
  doc.setFillColor(...BRAND.bluePanel);
  doc.roundedRect(totalsX, tableEndY, totalsBoxWidth, totalsBoxHeight, 8, 8, "FD");

  let totalsY = tableEndY + 22;
  const totalsRow = (
    label: string,
    value: string,
    opts: { bold?: boolean; accent?: boolean } = {},
  ) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.bold ? 12.5 : 10);
    if (opts.accent) doc.setTextColor(...BRAND.blueDark);
    else if (opts.bold) doc.setTextColor(...BRAND.ink);
    else doc.setTextColor(...BRAND.muted);
    doc.text(label, labelX, totalsY);
    doc.text(value, valueX, totalsY, { align: "right" });
    totalsY += opts.bold ? 22 : rowHeight;
  };

  totalsRow("Subtotal", fmtMoney(totals.subtotal, totals.currency));
  if (hasDiscount) {
    const discountLabel = totals.discount?.label
      ? `Discount (${totals.discount.label})`
      : "Discount";
    // ASCII hyphen — jsPDF's default Helvetica doesn't include the
    // Unicode minus glyph and renders it as spaced-out garbled text.
    totalsRow(discountLabel, `-${fmtMoney(totals.discountAmount, totals.currency)}`);
  }
  totalsRow("Tax", fmtMoney(totals.taxTotal, totals.currency));
  if (hasUpfrontCredit) {
    // Upfront fee credit. Conditional row mirroring the discount layout —
    // deducted from the post-tax total so the final figure matches what
    // the client owes net of the upfront fee they already paid.
    totalsRow(
      "Less upfront fee paid",
      `-${fmtMoney(upfrontCreditCents, totals.currency)}`,
    );
  }

  // Extra breathing room between Tax and Total — divider sits in the
  // middle of the gap, Total's bold 12.5pt cap-height needs clear space
  // above so it doesn't graze the divider line.
  totalsY += 8;
  doc.setDrawColor(...BRAND.blue);
  doc.setLineWidth(0.8);
  doc.line(labelX, totalsY - 12, valueX, totalsY - 12);
  doc.setLineWidth(0.5);
  totalsRow("Total", fmtMoney(totals.total, totals.currency), {
    bold: true,
    accent: true,
  });

  // ============== FOOTER BLOCKS ==============
  let footerY = tableEndY + totalsBoxHeight + 30;
  const writeBlock = (heading: string, body: string) => {
    if (!body.trim()) return;
    if (footerY > 700) {
      doc.addPage();
      footerY = margin;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...BRAND.blueDark);
    doc.text(heading.toUpperCase(), margin, footerY);
    footerY += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.ink);
    const lines = doc.splitTextToSize(body, pageWidth - margin * 2);
    doc.text(lines, margin, footerY);
    footerY += lines.length * 13 + 16;
  };

  if (summary.validUntil) {
    writeBlock("Validity", `Valid until ${summary.validUntil}.`);
  }
  if (summary.paymentInstructions)
    writeBlock("Payment instructions", summary.paymentInstructions);
  if (summary.terms) writeBlock("Terms / exclusions", summary.terms);

  // ============== FOOTER ==============
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BRAND.border);
    doc.line(margin, 758, pageWidth - margin, 758);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.muted);
    doc.text(
      "Generated by Blue Seal — blueseal.app",
      margin,
      772,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 772, {
      align: "right",
    });
  }

  return doc.output("blob");
}

export async function renderInvoicePdfBlob(
  invoice: WithId<InvoiceDoc>,
  party: PartyInfo,
): Promise<{ blob: Blob; filename: string }> {
  const blob = await renderPdf(
    {
      kind: "Invoice",
      number: invoice.invoiceNumber,
      issuedLabel: "Issued",
      issuedDate: fmtDate(invoice.issuedAt),
      paymentInstructions: invoice.paymentInstructions,
    },
    party,
    invoice.lineItems,
    {
      subtotal: invoice.subtotal,
      discount: invoice.discount,
      discountAmount: invoice.discountAmount,
      taxTotal: invoice.taxTotal,
      upfrontFeeCreditAmount: invoice.upfrontFeeCredit?.amountCents ?? 0,
      total: invoice.total,
      currency: invoice.currency || "CAD",
    },
  );
  return { blob, filename: `${invoice.invoiceNumber}.pdf` };
}

export async function renderQuotePdfBlob(
  quote: WithId<QuoteDoc>,
  party: PartyInfo,
): Promise<{ blob: Blob; filename: string }> {
  const blob = await renderPdf(
    {
      kind: "Quote",
      number: quote.quoteNumber,
      issuedLabel: "Sent",
      issuedDate: fmtDate(quote.sentAt ?? quote.issuedAt),
      validUntil: quote.validUntil ? fmtDate(quote.validUntil) : null,
      noteToClient: quote.noteToClient,
      terms: quote.terms,
    },
    party,
    quote.lineItems,
    {
      subtotal: quote.subtotal,
      discount: quote.discount ?? null,
      discountAmount: quote.discountAmount ?? 0,
      taxTotal: quote.taxTotal,
      total: quote.total,
      currency: quote.currency || "CAD",
    },
  );
  return { blob, filename: `${quote.quoteNumber}.pdf` };
}
