// Lazy-loaded PDF renderers for quotes + invoices.
//
// Returns a Blob so the caller can decide how to surface it (in-app
// preview modal, new tab, forced download). The actual jsPDF +
// jspdf-autotable imports live behind dynamic `import()` so the
// ~250 KB library only ships on first click.

import type {
  InvoiceDiscount,
  InvoiceDoc,
  LineItem,
  QuoteDoc,
  WithId,
} from "@/firebase/interfaces";
import type { Timestamp } from "firebase/firestore";

export interface PartyInfo {
  tradesperson: {
    name: string;
    companyName: string | null;
    // When set, the PDF header band renders this in place of the Blue Seal
    // wordmark + uses the tradesperson's company name as the headline. The
    // platform stays attributed in the footer ("Generated by Blue Seal").
    companyLogoUrl: string | null;
    // Custom branding (Blue Seal Pro). Already gated server-side in
    // getInvoicePartyInfo — these are null for non-Pro tradespeople, so the
    // renderer can use them directly. brandColor is "#RRGGBB"; bannerUrl is a
    // wide letterhead image.
    brandColor?: string | null;
    bannerUrl?: string | null;
    address: string | null;
    phone: string | null;
    email: string | null;
    gstNumber: string | null;
  };
  client: {
    name: string;
    email: string | null;
    phone: string | null;
    address: string | null;
  };
}

interface RenderTotals {
  subtotal: number;
  discount: InvoiceDiscount | null;
  discountAmount: number;
  taxTotal: number;
  /**
   * Upfront fee that was already collected and is being credited against this
   * invoice. Optional + zero-tolerant so quote rendering (which never carries
   * a credit) doesn't have to thread an extra value through.
   */
  upfrontFeeCreditAmount?: number;
  total: number;
  currency: string;
}

interface DocSummary {
  kind: "Quote" | "Invoice";
  number: string;
  issuedLabel: string;
  issuedDate: string;
  validUntil?: string | null;
  noteToClient?: string | null;
  paymentInstructions?: string | null;
  terms?: string | null;
}

// Brand palette — pulled into the PDF as RGB tuples so the rendered
// file is self-contained. Mirrors the CSS custom properties in
// src/assets/main.css so on-screen and on-paper Blue Seal feel like
// the same brand.
//   --bs-blue-dark   #2A3A5C → header band, table head, accents
//   --bs-blue        #374C76 → secondary band, links
//   --bs-blue-light  #B3DCFF → ultra-soft panels
//   --bs-amber       #D49A2E → total highlight (rating gold)
//   --bs-bg          #FDF8EC → paper-alt panels (soft warm paper)
const BRAND = {
  blueDark: [42, 58, 92] as const, // #2A3A5C
  blue: [55, 76, 118] as const, // #374C76
  blueLight: [179, 220, 255] as const, // #B3DCFF
  bluePanel: [235, 237, 241] as const, // computed ~10% mix of navy on white
  amber: [212, 154, 46] as const, // #D49A2E
  ink: [73, 76, 79] as const, // #494C4F
  muted: [102, 98, 87] as const, // #666257
  border: [224, 212, 184] as const, // #E0D4B8
  paperAlt: [253, 248, 236] as const, // #FDF8EC
};

// --- Custom-branding colour helpers (Blue Seal Pro) ---
// Parse "#RGB" / "#RRGGBB" → an [r,g,b] tuple, or null when it's not valid hex.
function hexToRgb(hex: string | null | undefined): [number, number, number] | null {
  if (!hex) return null;
  let h = hex.trim().replace(/^#/, "");
  if (h.length === 3)
    h = h
      .split("")
      .map((c) => c + c)
      .join("");
  if (!/^[0-9a-fA-F]{6}$/.test(h)) return null;
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

// Relative luminance (0..1) — used to pick readable text over the brand colour.
function luminance([r, g, b]: readonly [number, number, number]): number {
  const f = (c: number) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}

// Darken each channel (factor < 1) for the accent strip under the band.
function shade(
  [r, g, b]: readonly [number, number, number],
  factor: number,
): [number, number, number] {
  return [Math.round(r * factor), Math.round(g * factor), Math.round(b * factor)];
}

function fmtMoney(cents: number, currency = "CAD"): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency,
  }).format(cents / 100);
}

function fmtDate(t: Timestamp | null | undefined): string {
  if (!t) return "—";
  return new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(t.toDate());
}

// Module-level cache so the logo PNG is only fetched + base64-encoded
// once per page session. The data URL stays in memory for the rest of
// the tab's lifetime.
let logoDataUrlCache: string | null = null;
async function loadLogoDataUrl(): Promise<string | null> {
  if (logoDataUrlCache) return logoDataUrlCache;
  try {
    const res = await fetch("/icons/blueseal_logoCircle_RED.png");
    if (!res.ok) return null;
    const blob = await res.blob();
    const reader = new FileReader();
    const dataUrl = await new Promise<string>((resolve, reject) => {
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
    logoDataUrlCache = dataUrl;
    return dataUrl;
  } catch {
    return null;
  }
}

// Fetches a remote image (typically a Firebase Storage download URL) and
// returns a base64 data URL suitable for jsPDF's addImage. No cache — the
// tradesperson logo URL changes when they re-upload, and we want the next
// render to reflect that. Returns null on any failure so the caller can
// fall back to the platform Blue Seal mark.
async function loadRemoteImageAsDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    const reader = new FileReader();
    return await new Promise<string>((resolve, reject) => {
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// jsPDF addImage takes a format hint; infer it from the data URL prefix so
// callers don't have to worry about WebP-vs-PNG-vs-JPEG. Falls back to
// "PNG" which jsPDF always supports.
function inferImageFormat(dataUrl: string): string {
  const match = /^data:image\/([a-z]+);/i.exec(dataUrl);
  if (!match) return "PNG";
  const fmt = match[1].toUpperCase();
  return fmt === "JPG" ? "JPEG" : fmt;
}

async function renderPdf(
  summary: DocSummary,
  party: PartyInfo,
  lineItems: LineItem[],
  totals: RenderTotals,
): Promise<Blob> {
  // Lazy-imports keep the main bundle slim. jspdf-autotable mutates the
  // jsPDF instance, so it has to be imported after jsPDF. Tradie logo is
  // loaded in parallel; falls back to the platform Blue Seal mark when
  // unset or the fetch fails.
  const tradieLogoUrl = party.tradesperson.companyLogoUrl;
  const bannerUrl = party.tradesperson.bannerUrl ?? null;
  const [{ jsPDF }, autoTableMod, blueSealLogoDataUrl, tradieLogoDataUrl, bannerDataUrl] =
    await Promise.all([
      import("jspdf"),
      import("jspdf-autotable"),
      loadLogoDataUrl(),
      tradieLogoUrl ? loadRemoteImageAsDataUrl(tradieLogoUrl) : Promise.resolve(null),
      bannerUrl ? loadRemoteImageAsDataUrl(bannerUrl) : Promise.resolve(null),
    ]);
  const autoTable = autoTableMod.default;

  // Branding palette (Pro). brandColor is null server-side for non-Pro, so the
  // band falls back to Blue Seal navy. Text colour is contrast-picked so a
  // light brand colour stays readable.
  const brandRgb = hexToRgb(party.tradesperson.brandColor);
  const bandRgb: [number, number, number] = brandRgb ?? [42, 58, 92]; // BRAND.blueDark
  const accentRgb: [number, number, number] = brandRgb ? shade(brandRgb, 0.78) : [55, 76, 118]; // BRAND.blue
  const onBandDark = luminance(bandRgb) < 0.55;
  const titleColor: [number, number, number] = onBandDark ? [255, 255, 255] : [73, 76, 79];
  const subtitleColor: [number, number, number] = onBandDark ? [219, 228, 242] : [102, 98, 87];

  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;

  // ============== HEADER ==============
  // Default: a Blue Seal navy band with the logo + wordmark. Pro branding
  // (gated server-side) swaps in the tradesperson's brand colour; a banner
  // becomes a full-width letterhead with a slim doc-number strip beneath it.
  let headerBottom: number;
  if (bannerDataUrl) {
    const bannerH = 70;
    const stripH = 38;
    try {
      doc.addImage(bannerDataUrl, inferImageFormat(bannerDataUrl), 0, 0, pageWidth, bannerH);
    } catch {
      /* malformed banner — skip it; the strip below still anchors the header */
    }
    doc.setFillColor(...bandRgb);
    doc.rect(0, bannerH, pageWidth, stripH, "F");
    const midY = bannerH + stripH / 2;
    const companyTitle = party.tradesperson.companyName?.trim() || party.tradesperson.name;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...titleColor);
    doc.text(companyTitle, margin, midY + 3.5);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`${summary.kind.toUpperCase()} ${summary.number}`, pageWidth - margin, midY - 1, {
      align: "right",
    });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...subtitleColor);
    doc.text(`${summary.issuedLabel}: ${summary.issuedDate}`, pageWidth - margin, midY + 9, {
      align: "right",
    });
    headerBottom = bannerH + stripH;
  } else {
    // Brand band uses the brand colour (or Blue Seal navy) with a thin darker
    // accent strip underneath for depth. 88pt tall so the logo + wordmark have
    // room without crowding the doc-number on the right.
    const bandHeight = 88;
    const accentY = bandHeight - 6;
    doc.setFillColor(...bandRgb);
    doc.rect(0, 0, pageWidth, bandHeight, "F");
    doc.setFillColor(...accentRgb);
    doc.rect(0, accentY, pageWidth, 6, "F");

    // Logo on the left (38pt square). The tradesperson's logo takes the slot
    // when set (Pro), and their company name becomes the wordmark; otherwise
    // the Blue Seal mark + wordmark. Platform attribution stays in the footer.
    const logoSize = 38;
    const logoX = margin;
    const logoY = 24;
    let textXAfterLogo = margin;
    const headerLogoDataUrl = tradieLogoDataUrl ?? blueSealLogoDataUrl;
    if (headerLogoDataUrl) {
      try {
        doc.addImage(
          headerLogoDataUrl,
          inferImageFormat(headerLogoDataUrl),
          logoX,
          logoY,
          logoSize,
          logoSize,
        );
        textXAfterLogo = logoX + logoSize + 14;
      } catch {
        /* image add can fail on malformed data URL — fall back to text-only */
      }
    }

    const usingTradieLogo = tradieLogoDataUrl != null;
    const wordmarkTitle = usingTradieLogo
      ? party.tradesperson.companyName?.trim() || party.tradesperson.name
      : "Blue Seal";
    const wordmarkSubtitle = usingTradieLogo ? "Verified Tradesperson" : "Verified Trades";
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(...titleColor);
    doc.text(wordmarkTitle, textXAfterLogo, 44);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...subtitleColor);
    doc.text(wordmarkSubtitle, textXAfterLogo, 58);

    // Doc kind + number on the right
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...subtitleColor);
    doc.text(summary.kind.toUpperCase(), pageWidth - margin, 32, { align: "right" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...titleColor);
    doc.text(summary.number, pageWidth - margin, 52, { align: "right" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...subtitleColor);
    doc.text(`${summary.issuedLabel}: ${summary.issuedDate}`, pageWidth - margin, 68, {
      align: "right",
    });
    headerBottom = bandHeight;
  }

  // ============== FROM / BILL TO PANEL ==============
  // Two columns sitting just below the header band. Soft panels with
  // a subtle border so the contact info reads as its own block without
  // shouting against the brand colour.
  const panelY = headerBottom + 24;
  const panelGap = 16;
  const colWidth = (pageWidth - margin * 2 - panelGap) / 2;
  const leftX = margin;
  const rightX = margin + colWidth + panelGap;
  const panelPadX = 14;
  const panelPadY = 14;
  // Fixed-height panel sized to fit: heading + name + companyName + up to
  // 4 contact lines (address, phone, email, GST/HST) without overflow.
  const panelHeight = 112;

  doc.setDrawColor(...BRAND.border);
  doc.setFillColor(...BRAND.paperAlt);
  doc.roundedRect(leftX, panelY, colWidth, panelHeight, 6, 6, "FD");
  doc.roundedRect(rightX, panelY, colWidth, panelHeight, 6, 6, "FD");

  const writePartyBlock = (
    x: number,
    heading: string,
    name: string,
    companyName: string | null,
    lines: Array<string | null>,
  ) => {
    let y = panelY + panelPadY + 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.blue);
    doc.text(heading, x + panelPadX, y);

    y += 14;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11.5);
    doc.setTextColor(...BRAND.ink);
    doc.text(name, x + panelPadX, y);

    if (companyName) {
      y += 13;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...BRAND.ink);
      doc.text(companyName, x + panelPadX, y);
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...BRAND.muted);
    for (const line of lines) {
      if (!line) continue;
      y += 12;
      const wrapped = doc.splitTextToSize(line, colWidth - panelPadX * 2);
      doc.text(wrapped, x + panelPadX, y);
      if (Array.isArray(wrapped) && wrapped.length > 1) {
        y += (wrapped.length - 1) * 11;
      }
    }
  };

  writePartyBlock(
    leftX,
    "FROM",
    party.tradesperson.name,
    party.tradesperson.companyName,
    [
      party.tradesperson.address,
      party.tradesperson.phone,
      party.tradesperson.email,
      // CRA documentary requirement — GST/HST registrants must show their
      // number on invoices for clients to claim input tax credits.
      party.tradesperson.gstNumber
        ? `GST/HST: ${party.tradesperson.gstNumber}`
        : null,
    ],
  );
  writePartyBlock(
    rightX,
    summary.kind === "Invoice" ? "BILL TO" : "PREPARED FOR",
    party.client.name,
    null,
    [
      party.client.address,
      party.client.phone,
      party.client.email,
    ],
  );

  let cursorY = panelY + panelHeight + 24;

  // Optional client note — italic pull-quote.
  if (summary.noteToClient) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.ink);
    const noteLines = doc.splitTextToSize(
      `"${summary.noteToClient}"`,
      pageWidth - margin * 2,
    );
    doc.text(noteLines, margin, cursorY);
    cursorY += noteLines.length * 13 + 14;
  }

  // ============== LINE ITEMS TABLE ==============
  // Line total includes tax — `Qty × Unit price × (1 + taxRate)` — so a
  // row with "Tax 13 %" visibly reflects that 13 % in its line total.
  // The pre-tax subtotal + tax breakdown still appears in the totals
  // card so the math stays auditable.
  const tableBody = lineItems.map((li) => {
    const lineSubtotal = li.quantity * li.unitPrice;
    const lineWithTax = Math.round(lineSubtotal * (1 + li.taxRate));
    return [
      li.description,
      li.quantity.toString(),
      fmtMoney(li.unitPrice, totals.currency),
      `${(li.taxRate * 100).toFixed(1)}%`,
      fmtMoney(lineWithTax, totals.currency),
    ];
  });

  autoTable(doc, {
    startY: cursorY,
    margin: { left: margin, right: margin },
    head: [["Description", "Qty", "Unit price", "Tax %", "Line total"]],
    body: tableBody,
    headStyles: {
      fillColor: [...BRAND.blueDark],
      textColor: 255,
      fontSize: 10,
      fontStyle: "bold",
      cellPadding: 10,
    },
    bodyStyles: {
      fontSize: 10,
      textColor: [...BRAND.ink],
      cellPadding: 10,
    },
    alternateRowStyles: { fillColor: [...BRAND.paperAlt] },
    columnStyles: {
      1: { halign: "right", cellWidth: 50 },
      2: { halign: "right", cellWidth: 90 },
      3: { halign: "right", cellWidth: 60 },
      4: { halign: "right", cellWidth: 90 },
    },
    theme: "plain",
    styles: { lineColor: [...BRAND.border], lineWidth: 0.5 },
  });

  // @ts-expect-error autoTable attaches lastAutoTable to the doc at runtime
  const tableEndY: number = (doc.lastAutoTable?.finalY ?? cursorY) + 18;

  // ============== TOTALS CARD ==============
  const totalsBoxWidth = 230;
  const totalsX = pageWidth - margin - totalsBoxWidth;
  const labelX = totalsX + 16;
  const valueX = totalsX + totalsBoxWidth - 16;
  const rowHeight = 18;
  const hasDiscount = totals.discountAmount > 0;
  const upfrontCreditCents = Math.max(0, totals.upfrontFeeCreditAmount ?? 0);
  const hasUpfrontCredit = upfrontCreditCents > 0;
  // subtotal + tax (+ discount) (+ upfront credit)
  const innerRows = 2 + (hasDiscount ? 1 : 0) + (hasUpfrontCredit ? 1 : 0);
  const totalsBoxHeight = innerRows * rowHeight + 50;

  doc.setDrawColor(...BRAND.border);
  doc.setFillColor(...BRAND.bluePanel);
  doc.roundedRect(totalsX, tableEndY, totalsBoxWidth, totalsBoxHeight, 8, 8, "FD");

  let totalsY = tableEndY + 22;
  const totalsRow = (
    label: string,
    value: string,
    opts: { bold?: boolean; accent?: boolean } = {},
  ) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.bold ? 12.5 : 10);
    if (opts.accent) doc.setTextColor(...BRAND.blueDark);
    else if (opts.bold) doc.setTextColor(...BRAND.ink);
    else doc.setTextColor(...BRAND.muted);
    doc.text(label, labelX, totalsY);
    doc.text(value, valueX, totalsY, { align: "right" });
    totalsY += opts.bold ? 22 : rowHeight;
  };

  totalsRow("Subtotal", fmtMoney(totals.subtotal, totals.currency));
  if (hasDiscount) {
    const discountLabel = totals.discount?.label
      ? `Discount (${totals.discount.label})`
      : "Discount";
    // ASCII hyphen — jsPDF's default Helvetica doesn't include the
    // Unicode minus glyph and renders it as spaced-out garbled text.
    totalsRow(discountLabel, `-${fmtMoney(totals.discountAmount, totals.currency)}`);
  }
  totalsRow("Tax", fmtMoney(totals.taxTotal, totals.currency));
  if (hasUpfrontCredit) {
    // Upfront fee credit. Conditional row mirroring the discount layout —
    // deducted from the post-tax total so the final figure matches what
    // the client owes net of the upfront fee they already paid.
    totalsRow(
      "Less upfront fee paid",
      `-${fmtMoney(upfrontCreditCents, totals.currency)}`,
    );
  }

  // Extra breathing room between Tax and Total — divider sits in the
  // middle of the gap, Total's bold 12.5pt cap-height needs clear space
  // above so it doesn't graze the divider line.
  totalsY += 8;
  doc.setDrawColor(...BRAND.blue);
  doc.setLineWidth(0.8);
  doc.line(labelX, totalsY - 12, valueX, totalsY - 12);
  doc.setLineWidth(0.5);
  totalsRow("Total", fmtMoney(totals.total, totals.currency), {
    bold: true,
    accent: true,
  });

  // ============== FOOTER BLOCKS ==============
  let footerY = tableEndY + totalsBoxHeight + 30;
  const writeBlock = (heading: string, body: string) => {
    if (!body.trim()) return;
    if (footerY > 700) {
      doc.addPage();
      footerY = margin;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...BRAND.blueDark);
    doc.text(heading.toUpperCase(), margin, footerY);
    footerY += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND.ink);
    const lines = doc.splitTextToSize(body, pageWidth - margin * 2);
    doc.text(lines, margin, footerY);
    footerY += lines.length * 13 + 16;
  };

  if (summary.validUntil) {
    writeBlock("Validity", `Valid until ${summary.validUntil}.`);
  }
  if (summary.paymentInstructions)
    writeBlock("Payment instructions", summary.paymentInstructions);
  if (summary.terms) writeBlock("Terms / exclusions", summary.terms);

  // ============== FOOTER ==============
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...BRAND.border);
    doc.line(margin, 758, pageWidth - margin, 758);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND.muted);
    doc.text(
      "Generated by Blue Seal — blueseal.app",
      margin,
      772,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 772, {
      align: "right",
    });
  }

  return doc.output("blob");
}

export async function renderInvoicePdfBlob(
  invoice: WithId<InvoiceDoc>,
  party: PartyInfo,
): Promise<{ blob: Blob; filename: string }> {
  const blob = await renderPdf(
    {
      kind: "Invoice",
      number: invoice.invoiceNumber,
      issuedLabel: "Issued",
      issuedDate: fmtDate(invoice.issuedAt),
      paymentInstructions: invoice.paymentInstructions,
    },
    party,
    invoice.lineItems,
    {
      subtotal: invoice.subtotal,
      discount: invoice.discount,
      discountAmount: invoice.discountAmount,
      taxTotal: invoice.taxTotal,
      upfrontFeeCreditAmount: invoice.upfrontFeeCredit?.amountCents ?? 0,
      total: invoice.total,
      currency: invoice.currency || "CAD",
    },
  );
  return { blob, filename: `${invoice.invoiceNumber}.pdf` };
}

export async function renderQuotePdfBlob(
  quote: WithId<QuoteDoc>,
  party: PartyInfo,
): Promise<{ blob: Blob; filename: string }> {
  const blob = await renderPdf(
    {
      kind: "Quote",
      number: quote.quoteNumber,
      issuedLabel: "Sent",
      issuedDate: fmtDate(quote.sentAt ?? quote.issuedAt),
      validUntil: quote.validUntil ? fmtDate(quote.validUntil) : null,
      noteToClient: quote.noteToClient,
      terms: quote.terms,
    },
    party,
    quote.lineItems,
    {
      subtotal: quote.subtotal,
      discount: quote.discount ?? null,
      discountAmount: quote.discountAmount ?? 0,
      taxTotal: quote.taxTotal,
      total: quote.total,
      currency: quote.currency || "CAD",
    },
  );
  return { blob, filename: `${quote.quoteNumber}.pdf` };
}
